version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    reviewers:
      - '@Sofie-Automation/operations'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    reviewers:
      - '@Sofie-Automation/operations'
    # Only create security updates
    open-pull-requests-limit: 0
