name: Publish Docker

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tagName:
        description: 'Tag name to push'
        default: 'nightly'
        type: string

jobs:
  build:
    name: Build and publish docker images
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: HTTP-server - Build Docker and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: apps/http-server/app/Dockerfile
          tags: sofietv/package-manager-http-server:${{ github.event.inputs.tagName }}
      - name: Quantel HTTP Transformer Proxy - Build Docker and push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: apps/quantel-http-transformer-proxy/app/Dockerfile
          tags: sofietv/package-manager-quantel-http-transformer-proxy:${{ github.event.inputs.tagName }}
